---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:
  - name: i want to install webserver
    apt:
      name: "{{mywebpackonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: i want to start apache2
    service:
      name: "{{mywebpackonubuntu}}"
      state: restarted
    when: ansible_os_family =="Debian"

  - name: i want to install webserver in RedHat nodes
    yum: 
      name: "{{mywebpackinredhat}}"
      state: present
    when: ansible_os_family =="RedHat"

  - name: i want to start webserver
    service:
       name: "{{mywebpackinredhat}}"
       state: started
    when: ansible_os_family =="RedHat"
